### PR TITLE
fix: Blocks memory leak (#100)

### PR DESCRIPTION
**Pull request by darind**
Related to #100

### CODE REVIEW

**Comment by brysem** [comment]
Hi @darind,

Thank you for your effort! I've tested this PR in one of the larger apps I've made. The issue from #100 still seems to be present.

I tested it by using the app as normal and monitoring memory usage.

I've also tested it with a button that executes the following piece of code. This piece of code dramatically increases memory usage in V8. In JSC it does not.
```js
var dispatch = function() {
    setTimeout(function() {
    for(var i=0; i < 100000; i++) {
        var p = new Promise((resolve, reject) => { resolve('') })
    }
    dispatch()
    }, 50)
}
dispatch();
```

**Comment by darind** [comment]
@brysem, by creating 100k promises every 50ms you are putting too much pressure on the JS engine. Here's the profiler graph when I reduce it to 5 seconds:

image

Make sure you leave some CPU cycles for the GC to complete.

**Comment by NathanaelA** [comment]
@darind - Did you try this runtime with a fresh NS app on a real device; I am doing a:

(Using latest TNS 8 cli)
- ns create demo --js        
- cd demo
- ns platform add ios --frameworkPath <this_compliled_version>
- ns run ios

And I am seeing on a real ios 14.2 (iPhone7) device:

image

I'm not sure if the memory is being freed to early and so we are getting corrupted data back or what exactly...

**Comment by darind** [comment]
@NathanaelA, no I haven’t tried this on a real device in a fresh NS app. Does this crash occur in the Simulator?

But looking at the error, this looks like some issue with passing C strings as arguments to functions: https://github.com/NativeScript/ns-v8ios-runtime/blob/master/NativeScript/runtime/Interop.mm#L150

Are you sure that the crash doesn’t occur with a build from the master branch? Also is the use of the NSGetSizeAndAlignment function something new to the NS 8 core modules? Has this function been used before?

**Comment by NathanaelA** [comment]
@darind - 
> Does this crash occur in the Simulator?

Unknown, I can try a simulator if you need; I just tend to use a real device for most my testing.

> Are you sure that the crash doesn’t occur with a build from the master branch? 

Yes, to be honest, I thought it was my build initially, but I finally went back to `master` and built it and it worked, then I built another version with the other two outstanding PR's and both those worked.   However, the two different builds that I tried  that included this specific PR caused the above error.

> Also is the use of the NSGetSizeAndAlignment function something new to the NS 8 core modules? Has this function been used before?

That command does not appear to exist in the source code directly, I believe it is a side effect of the transition invocation.   However the area that the call stack points to hasn't been changed in a long time (I believe this code has remained unchanged and existed before NS6, but for sure it has existed for all of NS7)

**Comment by NathanaelA** [comment]
@darind - Hold off, I'm now really confused.  (BTW: The broken builds also don't work on simulators.)    Going to re-checkout master, and re-do all the builds and see what happens.   

I know the second build I created yesterday was only this PR, but I just created another new build using just this PR and it is working.      So, give me a bit of time to figure out what is different between the multiple branches I've created...

**Comment by NathanaelA** [comment]
@darind - I apologize; it isn't your PR.  Sorry to waste your time.    It is actually one of the other PR's, I suspect some how I got build artifacts from my first build where I included all three PR's...   Today after making sure everything is cleaned each time I narrowed down which PR properly)

**Comment by NathanWalker** [comment]
This pr is rolled up in https://github.com/NativeScript/ns-v8ios-runtime/pull/111 and in `rc` for further validations.

**Pull request closed without merging**
